services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - inception_network

  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - inception_network

  website:
    build: ./requirements/bonus/website/
    image: website:inception
    container_name: website
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - inception_network
  
  adminer:
    build: ./requirements/bonus/adminer/
    image: adminer:inception
    container_name: adminer
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    networks:
      - inception_network

  portainer:
    build: ./requirements/bonus/portainer
    image: portainer:inception
    container_name: portainer
    restart: on-failure
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception_network

  redis:
    build: ./requirements/bonus/redis
    image: redis:inception
    container_name: redis
    restart: on-failure
    networks:
      - inception_network

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:inception
    container_name: ftp
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress_files:/var/www/html
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - inception_network

volumes:
  mariadb_data:
    driver_opts:
      type: none
      o: bind
      device: /home/yaboukir/data/mariadb

  wordpress_files:
    driver_opts:
      type: none
      o: bind
      device: /home/yaboukir/data/wordpress

  portainer_data:
    driver_opts:
      type: none
      o: bind
      device: /home/yaboukir/data/portainer

networks:
  inception_network:
    driver: bridge
