services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception_network

  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: on-failure
    ports:
      - "6969:443"
    volumes:
      - wordpress_files:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - inception_network

  website:
    build: ./requirements/bonus/website/
    image: static-website:inception
    container_name: static-website
    restart: on-failure
    ports:
      - "6666:8090"
    networks:
      - inception_network
  
  adminer:
    build: ./requirements/bonus/adminer/
    image: adminer:inception
    container_name: adminer
    restart: on-failure
    ports:
      - "6699:5050"
    depends_on:
      - mariadb
    networks:
      - inception_network

volumes:
  mariadb_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

  wordpress_files:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception_network:
    driver: bridge